import ReactMarkDown from 'react-markdown';
const termOfServiceContent = `
# Terms of Service

## Legal Information

This service ("Faist") is provided by [Your Name], Auto-entrepreneur
- SIRET: [Your SIRET Number]
- Address: 11 rue des bergeres, Les Ulis, France
- Email: [privacy@faist.com]

## 1. Agreement to Terms

By accessing and using Faist's AI chat service ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of these terms, you may not access the Service.

## 2. Who Can Use the Service

To use the Service, you must:
- Be at least 16 years old
- Register with accurate information
- Be able to form a legally binding contract
- Not be prohibited from using the Service under applicable law

## 3. Service Description

### 3.1 General Service
Faist is an AI-powered chat service that allows users to interact with artificial intelligence models.

### 3.2 Free Plan Limitations
- Limited to 20 messages
- Message length and complexity restrictions may apply
- Features may be limited compared to Premium plan

### 3.3 Premium Features
- Unlimited messages
- Access to all AI models
- Priority support
- Additional features as described on our pricing page

## 4. Subscription and Payments

### 4.1 Payment Processing
- Payments are processed securely through Stripe
- By subscribing, you authorize recurring monthly charges
- All payment information is handled directly by Stripe

### 4.2 Subscription Terms
- Monthly subscription with automatic renewal
- Cancellation takes effect immediately
- Prorated refunds available upon cancellation
- Prices are subject to change with notice

## 5. User Obligations

You agree not to:
- Use the Service for any illegal purpose
- Share or sell account access
- Attempt to circumvent any service limitations
- Use automated systems to access the Service
- Create multiple accounts to bypass restrictions
- Harass, abuse, or harm others
- Violate any intellectual property rights

## 6. Data and Privacy

- We process personal data as described in our Privacy Policy
- You retain ownership of your content
- We maintain the right to use anonymized data for service improvement

## 7. Service Availability

- We strive for high availability but don't guarantee 100% uptime
- We may modify or discontinue features with notice
- Service may be interrupted for maintenance
- We're not liable for any service interruptions

## 8. Support and Communication

### 8.1 Customer Support
- Available via email and Discord
- Response times not guaranteed
- Premium users receive priority support

### 8.2 Claims and Disputes
- Initial contact through support channels
- We aim to resolve issues within 72 hours
- Users retain right to contact relevant authorities

## 9. Termination

We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason including:
- Terms of Service violations
- Suspected fraudulent activity
- Abusive behavior
- Non-payment

## 10. Liability and Disclaimers

- Service provided "as is"
- No warranty of continuous availability
- Not liable for damages arising from service use
- Not responsible for content generated by AI

## 11. Changes to Terms

We reserve the right to modify these terms at any time. We will notify users of any material changes via:
- Email notification
- Service announcement
- Website notice

## 12. Governing Law

These Terms shall be governed by French law. Any disputes shall be subject to the exclusive jurisdiction of the French courts.

## 13. Contact Information

Faist
11 rue des bergeres
Les Ulis, France

---

If you have any questions about these Terms, please contact us.
`;

export default function () {
  return (
    <ReactMarkDown>
      {termOfServiceContent}
    </ReactMarkDown>
  );
}
